apiVersion: v1
kind: Service
metadata:
  name: api-service
  namespace: proyecto-integrador
  labels:
    app: api
    tier: backend
spec:
  type: ClusterIP
  selector:
    app: api
  ports:
  - port: 8080
    targetPort: 8080
    protocol: TCP
    name: http
