apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
  namespace: proyecto-integrador
  labels:
    app: redis
    tier: cache
    version: v2.0
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
        tier: cache
        version: v2.0
    spec:
      containers:
      - name: redis
        image: redis:7-alpine
        ports:
        - containerPort: 6379
          name: redis
          protocol: TCP

        command:
        - redis-server
        - --appendonly
        - "yes"
        - --maxmemory
        - "128mb"
        - --maxmemory-policy
        - allkeys-lru

        livenessProbe:
          tcpSocket:
            port: 6379
          initialDelaySeconds: 15
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3

        readinessProbe:
          exec:
            command:
            - redis-cli
            - ping
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 3

        startupProbe:
          tcpSocket:
            port: 6379
          initialDelaySeconds: 0
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 30

        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"

        securityContext:
          runAsNonRoot: true
          runAsUser: 999  # redis user in alpine image
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: false
