apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: proyecto-integrador
  labels:
    app: frontend
    tier: presentation
    version: v2.0
spec:
  replicas: 2
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
        tier: presentation
        version: v2.0
    spec:
      containers:
      - name: frontend
        image: alefiengo/angular-frontend:v2.0
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
          name: http
          protocol: TCP

        # Variables de entorno desde ConfigMap
        envFrom:
        - configMapRef:
            name: frontend-config

        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 10
          periodSeconds: 10
          timeoutSeconds: 3
          failureThreshold: 3

        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 3

        startupProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 0
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 30

        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"

        securityContext:
          runAsNonRoot: false  # nginx necesita ser root para crear directorios cache
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: false
