apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: proyecto-integrador
  labels:
    app: frontend
    tier: presentation
spec:
  type: ClusterIP  # Cambiado a ClusterIP (se accederá via Ingress)
  selector:
    app: frontend
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    name: http
