apiVersion: v1
kind: Service
metadata:
  name: postgres-headless
  namespace: tarea-clase7
  labels:
    app: postgres
spec:
  clusterIP: None
  selector:
    app: postgres
  ports:
    - port: 5432
      targetPort: 5432
      name: postgres