apiVersion: v1
kind: Service
metadata:
  name: postgres-headless
  namespace: proyecto-integrador
  labels:
    app: postgres
    tier: database
spec:
  type: ClusterIP
  clusterIP: None  # Headless service para StatefulSet
  selector:
    app: postgres
  ports:
  - port: 5432
    targetPort: 5432
    protocol: TCP
    name: postgres
