apiVersion: v1
kind: Service
metadata:
  name: redis-service
  namespace: proyecto-integrador
  labels:
    app: redis
    tier: cache
spec:
  type: ClusterIP
  selector:
    app: redis
  ports:
  - port: 6379
    targetPort: 6379
    protocol: TCP
    name: redis
